apiVersion: v1
kind: Service
metadata:
    name: dapp-multisend-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: dapp-multisend-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dapp-multisend-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dapp-multisend-nginx
    template:
        metadata:
            labels:
                app: dapp-multisend-nginx
        spec:
            containers:
                -   name: dapp-multisend-nginx
                    image: docker.pkg.github.com/extraton/dapp-multisend/dapp-multisend-nginx:0.1.2
                    ports: [{containerPort: 80}]
            imagePullSecrets:
                -   name: github-registry
